# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'Fetch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  # Pods for Fetch

  target 'FetchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FetchUITests' do
    # Pods for testing
  end

end
